/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai_bus;

/**
 *
 * @author 1322527
 */
public class Ai_Bus_UI extends javax.swing.JFrame {

    /**
     * Creates new form Ai_Bus_UI
     */
    public Ai_Bus_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        route1Header = new javax.swing.JLabel();
        route3Header = new javax.swing.JLabel();
        route2Header = new javax.swing.JLabel();
        goButton = new javax.swing.JToggleButton();
        bus3Label = new javax.swing.JLabel();
        bus1Label = new javax.swing.JLabel();
        bus2Label = new javax.swing.JLabel();
        bus1Passengers = new javax.swing.JLabel();
        bus2Passengers = new javax.swing.JLabel();
        bus3Passengers = new javax.swing.JLabel();
        route1Stop1Label = new javax.swing.JLabel();
        route1Stop2Label = new javax.swing.JLabel();
        route1Stop3Label = new javax.swing.JLabel();
        route1Stop4Label = new javax.swing.JLabel();
        route1Stop5Label = new javax.swing.JLabel();
        route2Stop1Label = new javax.swing.JLabel();
        route2Stop2Label = new javax.swing.JLabel();
        route2Stop3Label = new javax.swing.JLabel();
        route2Stop4Label = new javax.swing.JLabel();
        route2Stop5Label = new javax.swing.JLabel();
        route3Stop1Label = new javax.swing.JLabel();
        route3Stop2Label = new javax.swing.JLabel();
        route3Stop3Label = new javax.swing.JLabel();
        route3Stop4Label = new javax.swing.JLabel();
        route3Stop5Label = new javax.swing.JLabel();
        bus4Label = new javax.swing.JLabel();
        bus4Route = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        route1Header.setText("Route 1");
        getContentPane().add(route1Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 38, 79, 23));

        route3Header.setText("Route 3");
        getContentPane().add(route3Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 79, 23));

        route2Header.setText("Route 2");
        getContentPane().add(route2Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 79, 23));

        goButton.setText("Simulate Bus Routes");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        getContentPane().add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        bus3Label.setText("Bus 3 Passengers:");
        getContentPane().add(bus3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, 30));

        bus1Label.setText("Bus 1 Passengers:");
        getContentPane().add(bus1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 110, 30));

        bus2Label.setText("Bus 2 Passengers:");
        getContentPane().add(bus2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 30));

        bus1Passengers.setText("0");
        getContentPane().add(bus1Passengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        bus2Passengers.setText("0");
        getContentPane().add(bus2Passengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        bus3Passengers.setText("0");
        getContentPane().add(bus3Passengers, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        route1Stop1Label.setText("0");
        getContentPane().add(route1Stop1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));

        route1Stop2Label.setText("0");
        getContentPane().add(route1Stop2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        route1Stop3Label.setText("0");
        getContentPane().add(route1Stop3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        route1Stop4Label.setText("0");
        getContentPane().add(route1Stop4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        route1Stop5Label.setText("0");
        getContentPane().add(route1Stop5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        route2Stop1Label.setText("0");
        getContentPane().add(route2Stop1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        route2Stop2Label.setText("0");
        getContentPane().add(route2Stop2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        route2Stop3Label.setText("0");
        getContentPane().add(route2Stop3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, -1));

        route2Stop4Label.setText("0");
        getContentPane().add(route2Stop4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        route2Stop5Label.setText("0");
        getContentPane().add(route2Stop5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, -1, -1));

        route3Stop1Label.setText("0");
        getContentPane().add(route3Stop1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, -1, -1));

        route3Stop2Label.setText("0");
        getContentPane().add(route3Stop2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        route3Stop3Label.setText("0");
        getContentPane().add(route3Stop3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        route3Stop4Label.setText("0");
        getContentPane().add(route3Stop4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        route3Stop5Label.setText("0");
        getContentPane().add(route3Stop5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        bus4Label.setText("Bus 4 Chosen Route: ");
        getContentPane().add(bus4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, -1));

        bus4Route.setText("1");
        bus4Route.setToolTipText("");
        getContentPane().add(bus4Route, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ai_Bus_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ai_Bus_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ai_Bus_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ai_Bus_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ai_Bus_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bus1Label;
    private javax.swing.JLabel bus1Passengers;
    private javax.swing.JLabel bus2Label;
    private javax.swing.JLabel bus2Passengers;
    private javax.swing.JLabel bus3Label;
    private javax.swing.JLabel bus3Passengers;
    private javax.swing.JLabel bus4Label;
    private javax.swing.JLabel bus4Route;
    private javax.swing.JButton exitButton;
    private javax.swing.JToggleButton goButton;
    private javax.swing.JLabel route1Header;
    private javax.swing.JLabel route1Stop1Label;
    private javax.swing.JLabel route1Stop2Label;
    private javax.swing.JLabel route1Stop3Label;
    private javax.swing.JLabel route1Stop4Label;
    private javax.swing.JLabel route1Stop5Label;
    private javax.swing.JLabel route2Header;
    private javax.swing.JLabel route2Stop1Label;
    private javax.swing.JLabel route2Stop2Label;
    private javax.swing.JLabel route2Stop3Label;
    private javax.swing.JLabel route2Stop4Label;
    private javax.swing.JLabel route2Stop5Label;
    private javax.swing.JLabel route3Header;
    private javax.swing.JLabel route3Stop1Label;
    private javax.swing.JLabel route3Stop2Label;
    private javax.swing.JLabel route3Stop3Label;
    private javax.swing.JLabel route3Stop4Label;
    private javax.swing.JLabel route3Stop5Label;
    // End of variables declaration//GEN-END:variables
}
